# Generated by Django 3.0 on 2021-08-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portabilidade', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portabiliade',
            new_name='Portabilidade',
        ),
    ]
