# Generated by Django 3.0 on 2021-08-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portabilidade', '0002_auto_20210813_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='portabilidade',
            name='numero_portar',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
