# Generated by Django 3.0 on 2021-08-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portabilidade', '0003_portabilidade_numero_portar'),
    ]

    operations = [
        migrations.AddField(
            model_name='portabilidade',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
