# Generated by Django 3.0 on 2021-08-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portabilidade', '0004_portabilidade_data_solicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPortabilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Status da Portabilidade',
            },
        ),
    ]
