# Generated by Django 3.0 on 2021-08-16 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portabilidade', '0005_statusportabilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='portabilidade',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portabilidade.StatusPortabilidade'),
            preserve_default=False,
        ),
    ]
