# Generated by Django 3.0 on 2021-08-16 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portabilidade', '0006_portabilidade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='portabilidade',
            name='data_conclusao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portabilidade',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitante', to=settings.AUTH_USER_MODEL),
        ),
    ]
