# Generated by Django 3.0 on 2021-08-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portabilidade', '0010_auto_20210816_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='portabilidade',
            name='numero_sip',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
